version: '3.8'

networks:
  test-net:
    name: test-net
    external: true

services:
  clickhouse:
    image: clickhouse/clickhouse-server
    user: "101:101"
    networks:
      - test-net
    container_name: clickhouse
    hostname: clickhouse
    volumes:
      - ${PWD}/fs/volumes/clickhouse/etc/clickhouse-server/config.d/config.xml:/etc/clickhouse-server/config.d/config.xml
      - ${PWD}/fs/volumes/clickhouse/etc/clickhouse-server/users.d/users.xml:/etc/clickhouse-server/users.d/users.xml
      - ${PWD}/fs/volumes/clickhouse/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    ports:
      - "127.0.0.1:8123:8123"
      - "127.0.0.1:9000:9000"
  grafana:
    build: 
      context: ${PWD}/docker_files/
      dockerfile: grafana.Dockerfile
    container_name: grafana
    hostname: grafana
    networks:
      - test-net
    volumes:
      - ${PWD}/fs/volumes/grafana/etc/grafana/provisioning/datasources:/etc/grafana/provisioning/datasources
    ports:
      - "127.0.0.1:3000:3000"
    depends_on:
      - clickhouse
