server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: kafka-logs
    kafka:
      brokers:
        - kafka:29092
      topics:
        - topic-event-audit
      group_id: promtail-consumer-group
    pipeline_stages:
      - json:
          expressions:
            timestamp: timestamp
            level: level
            message: message
    relabel_configs:
      - source_labels: ['__meta_kafka_topic']
        target_label: topic
