repositories:
- name: stable
  url: https://charts.helm.sh/stable
- name: incubator
  url: https://charts.helm.sh/incubator
- name: kiwigrid
  url: https://kiwigrid.github.io
- name: kokuwa
  url: https://kokuwaio.github.io/helm-charts
- name: bitnami
  url: https://charts.bitnami.com/bitnami
- name: qryn-helm
  url: https://metrico.github.io/qryn-helm/
- name: grafana
  url: https://grafana.github.io/helm-charts

releases:
- name: clickhouse
  namespace: audit
  chart: bitnami/clickhouse
  version: 8.0.4
  values:
    - values-clickhouse.yaml
- name: qryn
  namespace: audit
  chart: qryn-helm/qryn-helm
  version: 0.1.9
  values:
    - values-qryn.yaml
- name: grafana
  namespace: audit
  chart: grafana/grafana
  version: 8.10.1
  values:
    - values-grafana.yaml
- name: alloy
  namespace: audit
  chart: grafana/alloy
  version: 0.12.1
  values:
    - values-alloy.yaml