image:
  repository: qxip/qryn
  tag: "3.2.39"

fullnameOverride: "qryn"

replicaCount: 1

service:
  type: ClusterIP
  port: 3100

resources:
  limits:
    cpu: 200m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 128Mi

ingress:
  enabled: false
  className: ""
  annotations: {}
    #   kubernetes.io/ingress.class: nginx
    #   nginx.ingress.kubernetes.io/force-ssl-redirect: 'true'
    #   nginx.ingress.kubernetes.io/auth-type: basic
    #   nginx.ingress.kubernetes.io/auth-secret: basic-auth
    #   nginx.ingress.kubernetes.io/auth-realm: 'Authentication Required'
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local
basicAuthPass: ""
  # needs APR1-MD5 password 
  # example user test, pass test 
  # "test:$apr1$vbY9pP6j$GruYGP/AoYR1RPQN8KshE."
env:
  CLICKHOUSE_SERVER: "clickhouse"
  CLICKHOUSE_PORT: "8123"
  CLICKHOUSE_DB: "qryn"
  CLICKHOUSE_AUTH: "qryn:supersecretpassword"
  # CLICKHOUSE_PROTO: "http"
  # CLICKHOUSE_TIMEFIELD: "record_datetime"
  # CLUSTER_NAME: ""
  # BULK_MAXAGE: "2000"
  # BULK_MAXSIZE: "5000"
  # BULK_MAXCACHE: "50000"
  # LABELS_DAYS: "7"
  # SAMPLES_DAYS: "7"
  # HOST: "0.0.0.0"
  # PORT: "3100"
  # QRYN_LOGIN: ""
  # QRYN_PASSWORD: ""
  # READONLY: "false"
  # OMIT_CREATE_TABLES: "false"
  # FASTIFY_BODYLIMIT: "5242880"
  # FASTIFY_REQUESTTIMEOUT: "0"
  # FASTIFY_MAXREQUESTS: "0"
  # FASTIFY_METRICS: "false"
  # ADVANCED_PROMETHEUS_MAX_SAMPLES: "5000000"
  # CORS_ALLOW_ORIGIN: 	"*"
  # TEMPO_SPAN: "24"
  # TEMPO_TAGTRACE: "false"
  # DEBUG: "false"
  # LOG_LEVEL: "info"
  # HASH: "xxhash64"
  # ALERTMAN_URL: "false"
  # ADVANCED_SAMPLES_ORDERING: "timestamp_ns"

