services:

  trino-coordinator:
    image: "trinodb/trino:367"
    container_name: trino
    ports:
      - '8080:8080'
    volumes:
      - ./trino/coordinator/etc:/etc/trino:ro
      - ./trino/metastore-data:/opt/metastore-data

  minio:
    hostname: minio
    image: 'minio/minio:RELEASE.2021-12-29T06-49-06Z'
    container_name: minio
    ports:
      - '9595:9000'   # API
      - '38000:38000' # console
    volumes:
      - ./minio-data:/data
    environment:
      MINIO_ROOT_USER: minio_access_key
      MINIO_ROOT_PASSWORD: minio_secret_key
    command: server /data --console-address ":38000"

  superset:
    # image: 'apache/superset:latest'
    build:
      context: ./superset
      dockerfile: Dockerfile
    ports:
      - "8088:8088"
    volumes:
      - ./superset-data:/app/superset_home
      - ./superset/superset_config.py:/app/pythonpath/superset_config.py:ro
    environment:
      SECRET_KEY: "your-very-secret-key"
      SUPERSET_CONFIG_PATH: "/app/pythonpath/superset_config.py"