apiVersion: apps/v1
kind: Deployment
metadata:
  name: s3-ingest
spec:
  replicas: 1
  selector:
    matchLabels:
      app: s3-ingest
  template:
    metadata:
      labels:
        app: s3-ingest
    spec:
      containers:
        - name: s3-ingest
          image: ghcr.io/infitx-org/audit-ingester:main
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              memory: "512Mi"
              cpu: "500m"
            limits:
              memory: "1Gi"
              cpu: "1"
          env:
            - name: KAFKA_BROKER
              value: "kafka.demo.svc.cluster.local:9092"
            - name: S3_ENDPOINT
              value: "http://minio:9000"
            - name: S3_BUCKET
              value: "audit-env1"
            - name: S3_ACCESS_KEY
              value: "admin"
            - name: S3_SECRET_KEY
              value: "admin123"
            - name: S3_FOLDER
              value: "orc"

---
