networks:
  test-net:
    name: test-net
    external: true

services:

  orc-kafka-s3-ingester:
    image: 'orc-kafka-s3-ingester:local'
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - test-net
    environment:
      KAFKA_BROKER: kafka:29092
      S3_ENDPOINT: http://minio:9000
      S3_ACCESS_KEY: minio_access_key
      S3_SECRET_KEY: minio_secret_key
      S3_BUCKET: audit-logs
      S3_FOLDER: some-env-orc
