apiVersion: apps/v1
kind: Deployment
metadata:
  name: trino
spec:
  replicas: 1
  selector:
    matchLabels:
      app: trino
  template:
    metadata:
      labels:
        app: trino
    spec:
      containers:
        - name: trino
          image: trinodb/trino:367
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          # resources:
          #   requests:
          #     memory: "512Mi"
          #     cpu: "500m"
          #   limits:
          #     memory: "1Gi"
          #     cpu: "1"
          env:
            - name: TEST
              value: "test"
          # lifecycle:
          #   postStart:
          #     exec:
          #       command:
          #         - /bin/sh
          #         - -c
          #         - "pip install trino"
          volumeMounts:
            - name: trino-catalog
              mountPath: /etc/trino/catalog
            - name: trino-config
              mountPath: /etc/trino/node.properties
              subPath: node.properties
            - name: trino-config
              mountPath: /etc/trino/jvm.config
              subPath: jvm.config
            - name: trino-config
              mountPath: /etc/trino/config.properties
              subPath: config.properties
            - name: trino-metastore
              mountPath: /opt/metastore-data
      volumes:
        - name: trino-metastore
          emptyDir: {}
        - name: trino-config
          configMap:
            name: trino-config
        - name: trino-catalog
          configMap:
            name: trino-catalog

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: trino-catalog
data:
  hive.properties: |
    connector.name=hive
    hive.metastore=file
    hive.metastore.catalog.dir=file:///opt/metastore-data
    hive.s3.path-style-access=true
    hive.s3.endpoint=http://minio:9000
    hive.s3.aws-access-key=admin
    hive.s3.aws-secret-key=admin123
    hive.s3.path-style-access=true
    hive.non-managed-table-writes-enabled=true
    # hive.s3.bucket-name=your-bucket
    hive.s3select-pushdown.enabled=true
    hive.ignore-absent-partitions=true
    # By default, we cannot drop table
    hive.allow-drop-table=true

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: trino-config
data:
  node.properties: |
    node.id=1
    node.environment=test
  jvm.config: |
    -server
    -Xmx2G
    -XX:-UseBiasedLocking
    -XX:+UseG1GC
    -XX:G1HeapRegionSize=32M
    -XX:+ExplicitGCInvokesConcurrent
    -XX:+ExitOnOutOfMemoryError
    -XX:-OmitStackTraceInFastThrow
    -XX:ReservedCodeCacheSize=512M
    -XX:PerMethodRecompilationCutoff=10000
    -XX:PerBytecodeRecompilationCutoff=10000
    -Djdk.attach.allowAttachSelf=true
    -Djdk.nio.maxCachedBufferSize=2000000
  config.properties: |
    coordinator=true
    #single node install config
    node-scheduler.include-coordinator=true
    http-server.http.port=8080
    discovery.uri=http://trino:8080

---

apiVersion: v1
kind: Service
metadata:
  name: trino
spec:
  selector:
    app: trino
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: http
  type: ClusterIP