version: '3.8'

networks:
  test-net:
    name: test-net
    external: true

services:
  qryn:
    image: qxip/qryn:latest
    ports:
      - "3100:3100"
    networks:
      - test-net
    environment:
      - CLICKHOUSE_SERVER=clickhouse-server
      - CLICKHOUSE_AUTH=qryn:supersecretpassword
      - CLICKHOUSE_DB=qryn
  clickhouse-server:
    image: clickhouse/clickhouse-server:latest
    container_name: clickhouse-server
    environment:
      - CLICKHOUSE_USER=qryn
      - CLICKHOUSE_PASSWORD=supersecretpassword
    ports:
      - 8123:8123
    networks:
      - test-net
    healthcheck:
      test: ['CMD', 'wget', '--spider', '-q', '127.0.0.1:8123/ping']
      interval: 1s
      timeout: 1s
      retries: 30

  # promtail:
  #   image: grafana/promtail:latest
  #   networks:
  #     - test-net
  #   volumes:
  #     - ./promtail-config.yaml:/etc/promtail/config.yml
  #   command: -config.file=/etc/promtail/config.yml
  #   depends_on:
  #     - qryn

  alloy:
    image: grafana/alloy:latest
    ports:
      - 22345:12345
      - 4317:4317
      - 4318:4318
    volumes:
      - ./config.alloy:/etc/alloy/config.alloy
      # - ./logs:/tmp/app-logs/
    command: run --server.http.listen-addr=0.0.0.0:12345 --storage.path=/var/lib/alloy/data /etc/alloy/config.alloy
    depends_on:
      - qryn
    networks:
      - test-net