version: '3.8'

networks:
  test-net:
    name: test-net
    external: true

services:
  loki:
    image: grafana/loki:3.2.2
    networks:
      - test-net
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    volumes:
      - ./loki-config.yaml:/etc/loki/local-config.yaml

  # grafana:
  #   image: grafana/grafana:11.4.0
  #   networks:
  #     - test-net
  #   ports:
  #     - "9993:3000"
  #   volumes:
  #     - ./grafana/provisioning/:/etc/grafana/provisioning/
  #   environment:
  #     - GF_SECURITY_ADMIN_USER=admin
  #     - GF_SECURITY_ADMIN_PASSWORD=admin
  #   depends_on:
  #     - loki

  promtail:
    image: grafana/promtail:latest
    networks:
      - test-net
    volumes:
      - ./promtail-config.yaml:/etc/promtail/config.yml
    command: -config.file=/etc/promtail/config.yml
    depends_on:
      - loki
