auth_enabled: false

server:
  http_listen_port: 3100
  grpc_listen_port: 9095

common:
  instance_addr: 127.0.0.1
  path_prefix: /loki
  storage:
    filesystem:
      chunks_directory: /loki/chunks
      rules_directory: /loki/rules
  replication_factor: 1
  ring:
    kvstore:
      store: inmemory

ingester:
  lifecycler:
    ring:
      kvstore:
        store: inmemory
  chunk_idle_period: 5m
  chunk_block_size: 262144
  chunk_retain_period: 30s
  # max_transfer_retries: 0

schema_config:
  configs:
    - from: 2020-10-24
      store: tsdb
      object_store: filesystem
      schema: v13
      index:
        prefix: index_
        period: 24h

# storage_config:
#   boltdb:
#     directory: /loki/index
#   filesystem:
#     directory: /loki/chunks

limits_config:
  # enforce_metric_name: false
  reject_old_samples: true
  reject_old_samples_max_age: 168h
  allow_structured_metadata: false
  ingestion_rate_mb: 100      # Increase this value (default is 4 MB per second)
  ingestion_burst_size_mb: 200 # Increase burst size for temporary spikes
  per_stream_rate_limit: 20MB           # Increase the per-stream rate limit (default is 3MB)
  per_stream_rate_limit_burst: 50MB    # Allow burst size for each stream
  max_global_streams_per_user: 0
  volume_enabled: true
# chunk_store_config:
#   max_look_back_period: 0
